using System.Collections.Generic;

namespace SharedDomain
{
    public class Answer : IVotable, IEqualityComparer<Answer>
    {
        public string Id { get; set; }
        public Player Player { get; set; }
        public string Name { get; set; }
        public List<Vote<Answer>> Votes { get; set; }
        public bool IsAutoGenerated { get; set; }

        public bool Equals(Answer x, Answer y)
        {
            return string.Equals(x.Id, y.Id);
        }

        public int GetHashCode(Answer obj)
        {
            return obj.Id.GetHashCode();
        }
    }
}