using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assets.Scripts.Reusable;
using Assets.Scripts.Services;
using SharedDomain;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.UI.Extensions;

namespace Assets.Scripts.Round
{
    public class AnswerScript : MonoBehaviour
    {
        private const string VotePrefab = "Prefabs/Vote";
        private const string AnswerPrefab = "Prefabs/Answer";

        public RectTransform VoteGrid;
        public TextMeshProUGUI TextTMP;
        public GameObject PlayerNameContainer;
        public TextMeshProUGUI PlayerName;
        public TextMeshProUGUI PointsTMP;

        private ConcurrentDictionary<string, VoteScript> votes;
        private Answer answer;
        private Animator animator;
        private AudioSource audioSource;
        private Image image;
        private RectTransform answerPositionReference;
        private NicerOutline outline;

        public string AnswerId => answer.Id;
        public int VoteCount => votes.Count;
        public string AnswerText => answer?.Name;
        public bool IsAutoGenerated => answer.IsAutoGenerated;
        public List<PlayerScript> AuthorPlayerScripts { get; private set; }
        public List<PlayerScript> VotePlayerScripts { get; private set; }
        public bool IsCorrect { get; private set; }

        private void Start()
        {
            votes = new ConcurrentDictionary<string, VoteScript>();
            VotePlayerScripts = new List<PlayerScript>();
            animator = GetComponent<Animator>();
            audioSource = GetComponent<AudioSource>();
            image = GetComponent<Image>();
            outline = GetComponent<NicerOutline>();
            answerPositionReference = GameObject.FindGameObjectWithTag("PositionReference").GetComponent<RectTransform>();
        }

        public void LoadAnswer(Answer answer, IEnumerable<PlayerScript> authorScripts, bool isCorrect = false)
        {
            this.answer = answer;
            TextTMP.text = AnswerText;
            IsCorrect = isCorrect;
            if (!isCorrect) AuthorPlayerScripts = authorScripts.ToList();
            gameObject.SetActive(true);
        }

        public void AddVote(Vote<Answer> vote)
        {
            var prefab = Resources.Load<GameObject>(VotePrefab);
            prefab.SetActive(false);

            var newVote = GameObject.Instantiate(prefab, VoteGrid);
            newVote.GetComponent<VoteScript>().PlayerName.text = vote.By.Nick;
            votes.TryAdd(vote.By.Id, newVote.GetComponent<VoteScript>());
        }

        public async Task ShowVotes()
        {
            var rectTransform = GetComponent<RectTransform>();

            audioSource.PlayOneShot(Resources.Load<AudioClip>(Constants.WhooshSlowDeep09SoundPath));

            transform.SetParent(FindObjectOfType<Canvas>().transform);
            transform.SetAsLastSibling();

            await rectTransform.AnimateMoveTowardsAsync(answerPositionReference.position, 1.2f, 7);

            if (votes.Count > 0)
            {
                VoteGrid.gameObject.SetActive(true);
                foreach (var vote in votes.Values) await vote.ShowAsync();
            }


            var cashRegisterSound = Constants.AudioClips.GetCashRegisterSound();
            var correctAnswerSound = Constants.AudioClips.GetCorrectAnswerSound();
            var failPartyHornSound = Constants.AudioClips.GetFailPartyHornSound();
            await new WaitForSeconds(0.7f); // Wait a bit before revealing the points

            if (IsCorrect)
            {
                PlayerName.text = "Correct lyric";
                PlayerNameContainer.SetActive(true);

                audioSource.PlayOneShot(votes.Count > 0 ? correctAnswerSound : failPartyHornSound);
                image.color = Constants.Colors.CorrectAnswerBackground;
                outline.effectColor = Constants.Colors.CorrectAnswerBorder;
                PlayerNameContainer.GetComponent<Image>().color = Constants.Colors.CorrectAnswerBorder;
                PlayerName.color = Constants.Colors.CorrectAnswerBackground;
                TextTMP.color = Constants.Colors.CorrectAnswerText;
                VoteGrid.GetComponent<Image>().color = Constants.Colors.CorrectAnswerBorder;

                foreach (var vote in votes.Values)
                foreach (var playerScript in VotePlayerScripts)
                    vote.ShowCorrectAsync(Constants.CorrectAnswerPoints).CatchErrors();


                await new WaitForSeconds(2.8f);
                gameObject.SetActive(false);
                return;
            }

            for (var i = 0; i < AuthorPlayerScripts.Count; i++)
            {
                var authorScript = AuthorPlayerScripts[i];
                if (i > 0)
                {
                    PlayerName.text = "ALSO";
                    await new WaitForSeconds(1f);
                }

                PlayerName.text = $"{authorScript.PlayerNick}'s lyric".ToUpper();
                if (!PlayerNameContainer.activeSelf) PlayerNameContainer.SetActive(true);

                var totalScore = votes.Sum(_ => IsAutoGenerated ? Constants.VotePoints / 2 : Constants.VotePoints);
                PointsTMP.text = $"+{totalScore}";
                PointsTMP.gameObject.SetActive(true);
                audioSource.PlayOneShot(cashRegisterSound);

                await new WaitForSeconds(2.5f);
            }

            gameObject.SetActive(false);
        }

        public async Task ShrinkAsync()
        {
            var clip = System.Array.Find(animator.runtimeAnimatorController.animationClips,
                a => a.name.Contains("ShrinkAnswer"));

            animator.Play(clip.name);

            await new WaitForSeconds(clip.length);
        }

        public async Task GrowBackAsync()
        {
            var clip = System.Array.Find(animator.runtimeAnimatorController.animationClips,
                a => a.name.Contains("GrowAnswerToNormal"));

            animator.Play(clip.name);
            await new WaitForSeconds(clip.length);
        }

        public static AnswerScript Instantiate(
            Answer answer,
            Transform parent,
            IEnumerable<PlayerScript> authorScripts,
            bool isCorrect = false)
        {
            var prefab = Resources.Load<GameObject>(AnswerPrefab);
            var instance = GameObject.Instantiate(prefab, parent).GetComponent<AnswerScript>();
            instance.LoadAnswer(answer, authorScripts, isCorrect);

            return instance;
        }
    }
}