namespace SharedDomain
{
    public static class WebClientMethods
    {
        public const string Ask = nameof(Ask);
        public const string StartVoting = nameof(StartVoting);
        public const string Relax = nameof(Relax);
        public const string EndGame = nameof(EndGame);
        public const string NotifyAutogeneratedAnswer = nameof(NotifyAutogeneratedAnswer);
        public const string RemoveRoom = nameof(RemoveRoom);
        public const string HostDisconnected = nameof(HostDisconnected);
        public const string Kick = nameof(Kick);
        public const string AskSpeed = nameof(AskSpeed);
    }
}