# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: true
  branches:
    include:
    - staging

pool:
  vmImage: ubuntu-latest

steps:

- task: DockerCompose@0
  displayName: "Build images"
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'GoogleContainerRegistry_STG'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
    arguments: 'backofficeweb'

- task: Docker@2
  displayName: "Tag backofficeweb"
  inputs:
    containerRegistry: 'GoogleContainerRegistry_STG'
    command: 'tag'
    arguments: 'us.gcr.io/music-staging-281310/backofficeweb:$(ENVIRONMENT_NAME) us.gcr.io/music-staging-281310/backofficeweb:$(Build.BuildNumber)'

- task: Docker@2
  displayName: "Push backofficeweb"
  inputs:
    containerRegistry: 'GoogleContainerRegistry_STG'
    repository: 'music-staging-281310/backofficeweb'
    command: 'push'
    tags: |
      $(Build.BuildNumber)
      $(ENVIRONMENT_NAME)  

- task: PostBuildCleanup@3