# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: true
  branches:
    include:
    - develop

pool:
  name: 'Google Cloud'
  demands: 
    - Environment -equals development

steps:

- task: DockerCompose@0
  displayName: "Build images"
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'GoogleContainerRegistry_DEV'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
    arguments: 'musicapiserverless'

- task: CmdLine@2
  displayName: Convert build nr . to _
  inputs:
    script: |
       buildnr=$( echo $(Build.BuildNumber) | tr "." _)
       echo $buildnr
       echo "##vso[task.setvariable variable=buildnr]$buildnr"

- task: Docker@2
  displayName: "Tag musicapiserverless"
  inputs:
    containerRegistry: 'GoogleContainerRegistry_DEV'
    command: 'tag'
    arguments: 'eu.gcr.io/supple-coral-271015/musicapiserverless:$(ENVIRONMENT_NAME) eu.gcr.io/supple-coral-271015/musicapiserverless:$(buildnr)'

- task: Docker@2
  displayName: "Push musicapiserverless"
  inputs:
    containerRegistry: 'GoogleContainerRegistry_DEV'
    repository: 'supple-coral-271015/musicapiserverless'
    command: 'push'
    tags: |
      $(buildnr)
      $(ENVIRONMENT_NAME)

- task: DownloadSecureFile@1
  name: SecureFKey
  inputs:
    secureFile: '$(KEY_FILE_NAME)'

- task: GcloudRunner@0
  displayName: Activate service account
  inputs:
    command: 'auth activate-service-account'
    arguments: '$(SERVICE_ACCOUNT_NAME) --key-file=$(SecureFKey.secureFilePath)'

- task: GcloudRunner@0
  displayName: Deploy new revision on gcloud run
  inputs:
    command: 'run deploy'
    arguments: '$(SERVICE_NAME) --image=eu.gcr.io/supple-coral-271015/musicapiserverless:$(ENVIRONMENT_NAME) --account=$(SERVICE_ACCOUNT_NAME) --platform managed --region europe-west4'

- task: GcloudRunner@0
  displayName: Logout Gcloud
  inputs:
    command: 'auth revoke'
    arguments: '$(SERVICE_ACCOUNT_NAME)'
- task: DownloadSecureFile@1
  displayName: Download SA key
  name: sa_key
  inputs:
    secureFile: 'gc_tf.json'

- task: GcloudRunner@0
  inputs:
    command: 'auth activate-service-account'
    arguments: '--key-file $(sa_key.secureFilePath)'

- task: GcloudRunner@0
  displayName: Adding labels with image ids
  inputs:
    command: 'compute instances add-labels'
    arguments: 'dev-euw-versesurf-001 --zone europe-west3-c --labels=mas_image_id=$(buildnr)'

- task: PostBuildCleanup@3